package routes

import (
	"gobase-app/controllers"
	"gobase-app/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterWebRoutes(r *gin.Engine) {
	r.Use(middleware.UserMiddleware())

	r.GET("/", controllers.LoginPage)
	r.GET("/login", controllers.LoginPage)
	r.POST("/login", controllers.LoginPost)
	r.GET("/logout", controllers.Logout)

	auth := r.Group("/")
	auth.Use(middleware.AuthRequired(), middleware.PermissionContext())
	{
		auth.GET("/profile", controllers.ProfileIndex)
		auth.POST("/profile", controllers.ProfileUpdate)
		auth.POST("/profile/password", controllers.ProfilePasswordUpdate)
		auth.GET("/dashboard", middleware.RequirePermission("dashboard_access"), controllers.DashboardIndex)
		auth.GET("/approval-tasks", middleware.RequirePermission("approval_task_management_access"), controllers.ApprovalTaskInboxIndex)
		auth.GET("/approval-tasks/:id", middleware.RequirePermission("approval_task_view"), controllers.ApprovalTaskDetail)
		auth.POST("/approval-tasks/:id/approve", middleware.RequirePermission("approval_task_approve"), controllers.ApprovalTaskApprove)
		auth.POST("/approval-tasks/:id/reject", middleware.RequirePermission("approval_task_reject"), controllers.ApprovalTaskReject)
		auth.GET("/purchase-requests", middleware.RequirePermission("purchase_request_management_access"), controllers.PurchaseRequestIndex)
		auth.GET("/purchase-requests/form", middleware.RequirePermission("purchase_request_create"), controllers.PurchaseRequestFormIndex)
		auth.GET("/purchase-requests/:id", middleware.RequirePermission("purchase_request_view"), controllers.PurchaseRequestDetailIndex)
		auth.POST("/purchase-requests/:id/update", middleware.RequirePermission("purchase_request_edit"), controllers.PurchaseRequestUpdate)
		auth.POST("/purchase-requests/:id/regenerate-approval", middleware.RequirePermission("purchase_request_management_access"), controllers.PurchaseRequestRegenerateApproval)
		auth.POST("/purchase-requests", middleware.RequirePermission("purchase_request_create"), controllers.PurchaseRequestStore)
		auth.GET("/purchase-orders", middleware.RequirePermission("purchase_order_management_access"), controllers.PurchaseOrderIndex)
		auth.GET("/purchase-orders/create-from-pr/:pr_id", middleware.RequirePermission("purchase_order_create"), controllers.PurchaseOrderCreateFromPR)
		auth.POST("/purchase-orders", middleware.RequirePermission("purchase_order_create"), controllers.PurchaseOrderStore)
		auth.GET("/purchase-orders/:id", middleware.RequirePermission("purchase_order_view"), controllers.PurchaseOrderDetailIndex)
		auth.GET("/asset-types", middleware.RequirePermission("asset_type_management_access"), controllers.AssetTypeIndex)
		auth.POST("/asset-types", middleware.RequirePermission("asset_type_create"), controllers.AssetTypeStore)
		auth.POST("/asset-types/update", middleware.RequirePermission("asset_type_edit"), controllers.AssetTypeUpdate)
		auth.GET("/asset-types/delete/:id", middleware.RequirePermission("asset_type_delete"), controllers.AssetTypeDelete)
		auth.GET("/asset-categories", middleware.RequirePermission("asset_category_management_access"), controllers.AssetCategoryIndex)
		auth.POST("/asset-categories", middleware.RequirePermission("asset_category_create"), controllers.AssetCategoryStore)
		auth.POST("/asset-categories/update", middleware.RequirePermission("asset_category_edit"), controllers.AssetCategoryUpdate)
		auth.POST("/asset-categories/delete/:id", middleware.RequirePermission("asset_category_delete"), controllers.AssetCategoryDelete)
		auth.GET("/component-types", middleware.RequirePermission("component_type_management_access"), controllers.ComponentTypeIndex)
		auth.POST("/component-types", middleware.RequirePermission("component_type_create"), controllers.ComponentTypeStore)
		auth.POST("/component-types/update", middleware.RequirePermission("component_type_edit"), controllers.ComponentTypeUpdate)
		auth.GET("/component-types/delete/:id", middleware.RequirePermission("component_type_delete"), controllers.ComponentTypeDelete)
		auth.GET("/asset-locations", middleware.RequirePermission("asset_location_management_access"), controllers.AssetLocationIndex)
		auth.POST("/asset-locations", middleware.RequirePermission("asset_location_create"), controllers.AssetLocationStore)
		auth.POST("/asset-locations/update", middleware.RequirePermission("asset_location_edit"), controllers.AssetLocationUpdate)
		auth.GET("/asset-locations/delete/:id", middleware.RequirePermission("asset_location_delete"), controllers.AssetLocationDelete)
		auth.GET("/asset-register", middleware.RequirePermission("asset_management_access"), controllers.AssetIndex)
		auth.POST("/asset-register", middleware.RequirePermission("asset_create"), controllers.AssetStore)
		auth.POST("/asset-register/update", middleware.RequirePermission("asset_edit"), controllers.AssetUpdate)
		auth.GET("/asset-register/detail/:id", middleware.RequirePermission("asset_management_access"), controllers.AssetDetailIndex)
		auth.GET("/asset-register/delete/:id", middleware.RequirePermission("asset_delete"), controllers.AssetDelete)
		auth.GET("/asset-components", middleware.RequirePermission("asset_component_management_access"), controllers.AssetComponentIndex)
		auth.GET("/asset-components/detail/:id", middleware.RequirePermission("asset_component_management_access"), controllers.AssetComponentDetailIndex)
		auth.POST("/asset-components", middleware.RequirePermission("asset_component_create"), controllers.AssetComponentStore)
		auth.POST("/asset-components/update", middleware.RequirePermission("asset_component_edit"), controllers.AssetComponentUpdate)
		auth.GET("/asset-components/delete/:id", middleware.RequirePermission("asset_component_delete"), controllers.AssetComponentDelete)
		auth.GET("/asset-movements", middleware.RequirePermission("asset_movement_management_access"), controllers.AssetMovementIndex)
		auth.POST("/asset-movements", middleware.RequirePermission("asset_movement_create"), controllers.AssetMovementStore)
		auth.GET("/asset-component-movements", middleware.RequirePermission("asset_component_movement_management_access"), controllers.AssetComponentMovementIndex)
		auth.POST("/asset-component-movements", middleware.RequirePermission("asset_component_movement_create"), controllers.AssetComponentMovementStore)
		auth.GET("/asset-depreciation/monthly", middleware.RequirePermission("asset_depreciation_management_access"), controllers.MonthlyDepreciationIndex)
		auth.POST("/asset-depreciation/monthly/generate", middleware.RequirePermission("asset_depreciation_generate"), controllers.MonthlyDepreciationGenerate)
		auth.POST("/asset-depreciation/monthly/post", middleware.RequirePermission("asset_depreciation_post"), controllers.MonthlyDepreciationPost)
		auth.POST("/asset-depreciation/monthly/skip", middleware.RequirePermission("asset_depreciation_skip"), controllers.MonthlyDepreciationSkip)
		auth.POST("/asset-depreciation/monthly/reverse", middleware.RequirePermission("asset_depreciation_reverse"), controllers.MonthlyDepreciationReverse)
		auth.POST("/asset-depreciation/monthly/correction", middleware.RequirePermission("asset_depreciation_correction_edit"), controllers.MonthlyDepreciationCorrectionUpdate)
		auth.POST("/asset-depreciation/monthly/close-period", middleware.RequirePermission("asset_depreciation_period_close"), controllers.MonthlyDepreciationPeriodClose)
		auth.POST("/asset-depreciation/monthly/reopen-period", middleware.RequirePermission("asset_depreciation_period_reopen"), controllers.MonthlyDepreciationPeriodReopen)
		auth.GET("/asset-depreciation/profiles", middleware.RequirePermission("asset_depreciation_profile_management_access"), controllers.DepreciationProfileIndex)
		auth.POST("/asset-depreciation/profiles/save", middleware.RequirePermission("asset_depreciation_profile_edit"), controllers.DepreciationProfileSave)
		auth.POST("/asset-depreciation/profiles/pause", middleware.RequirePermission("asset_depreciation_profile_pause"), controllers.DepreciationProfilePause)
		auth.POST("/asset-depreciation/profiles/resume", middleware.RequirePermission("asset_depreciation_profile_resume"), controllers.DepreciationProfileResume)
		auth.GET("/asset-depreciation/posting-history", middleware.RequirePermission("asset_depreciation_posting_history_access"), controllers.DepreciationPostingHistoryIndex)
		auth.GET("/asset-disposal-types", middleware.RequirePermission("asset_disposal_type_management_access"), controllers.AssetDisposalTypeIndex)
		auth.POST("/asset-disposal-types", middleware.RequirePermission("asset_disposal_type_create"), controllers.AssetDisposalTypeStore)
		auth.POST("/asset-disposal-types/update", middleware.RequirePermission("asset_disposal_type_edit"), controllers.AssetDisposalTypeUpdate)
		auth.POST("/asset-disposal-types/:id/delete", middleware.RequirePermission("asset_disposal_type_delete"), controllers.AssetDisposalTypeDelete)
		auth.GET("/asset-disposals", middleware.RequirePermission("asset_disposal_management_access"), controllers.AssetDisposalIndex)
		auth.POST("/asset-disposals", middleware.RequirePermission("asset_disposal_create"), controllers.AssetDisposalStore)
		auth.POST("/asset-disposals/update", middleware.RequirePermission("asset_disposal_edit"), controllers.AssetDisposalUpdate)
		auth.POST("/asset-disposals/:id/submit", middleware.RequirePermission("asset_disposal_submit"), controllers.AssetDisposalSubmit)
		auth.POST("/asset-disposals/:id/post", middleware.RequirePermission("asset_disposal_post"), controllers.AssetDisposalPost)
		auth.POST("/asset-disposals/:id/cancel", middleware.RequirePermission("asset_disposal_cancel"), controllers.AssetDisposalCancel)
		auth.POST("/asset-disposals/:id/reverse", middleware.RequirePermission("asset_disposal_reverse"), controllers.AssetDisposalReverse)
		auth.GET("/asset-disposal-approval/rules", middleware.RequirePermission("asset_disposal_approval_rule_management_access"), controllers.AssetDisposalApprovalRuleIndex)
		auth.POST("/asset-disposal-approval/rules", middleware.RequirePermission("asset_disposal_approval_rule_create"), controllers.AssetDisposalApprovalRuleStore)
		auth.POST("/asset-disposal-approval/rules/update", middleware.RequirePermission("asset_disposal_approval_rule_edit"), controllers.AssetDisposalApprovalRuleUpdate)
		auth.POST("/asset-disposal-approval/rules/:id/delete", middleware.RequirePermission("asset_disposal_approval_rule_delete"), controllers.AssetDisposalApprovalRuleDelete)
		auth.GET("/asset-disposal-approval/approvers", middleware.RequirePermission("asset_disposal_approver_management_access"), controllers.AssetDisposalApproverIndex)
		auth.POST("/asset-disposal-approval/approvers", middleware.RequirePermission("asset_disposal_approver_create"), controllers.AssetDisposalApproverStore)
		auth.POST("/asset-disposal-approval/approvers/update", middleware.RequirePermission("asset_disposal_approver_edit"), controllers.AssetDisposalApproverUpdate)
		auth.POST("/asset-disposal-approval/approvers/:id/delete", middleware.RequirePermission("asset_disposal_approver_delete"), controllers.AssetDisposalApproverDelete)
		auth.GET("/asset-disposal-approval/inbox", middleware.RequirePermission("asset_disposal_approval_inbox_access"), controllers.AssetDisposalApprovalInboxIndex)
		auth.POST("/asset-disposal-approval/tasks/:id/approve", middleware.RequirePermission("asset_disposal_approval_approve"), controllers.AssetDisposalApprovalTaskApprove)
		auth.POST("/asset-disposal-approval/tasks/:id/reject", middleware.RequirePermission("asset_disposal_approval_reject"), controllers.AssetDisposalApprovalTaskReject)
		auth.GET("/reports/asset-disposals", middleware.RequirePermission("asset_disposal_report_access"), controllers.AssetDisposalReportIndex)
		auth.GET("/reports/asset-disposals/export", middleware.RequirePermission("asset_disposal_report_export"), controllers.AssetDisposalReportExportCSV)
		auth.GET("/reports/asset-depreciation-annual", middleware.RequirePermission("asset_depreciation_annual_report_access"), controllers.AssetDepreciationAnnualReportIndex)
		auth.GET("/reports/asset-depreciation-annual/export", middleware.RequirePermission("asset_depreciation_annual_report_export"), controllers.AssetDepreciationAnnualReportExportCSV)

		auth.POST("/register", middleware.RequirePermission("user_create"), controllers.CreateUser)
		auth.GET("/stores", middleware.RequirePermission("store_management_access"), controllers.StoreIndex)
		auth.POST("/stores", middleware.RequirePermission("store_create"), controllers.StoreStore)
		auth.POST("/stores/update", middleware.RequirePermission("store_edit"), controllers.StoreUpdate)
		auth.GET("/stores/delete/:id", middleware.RequirePermission("store_delete"), controllers.StoreDelete)
		auth.GET("/vendors", middleware.RequirePermission("vendor_management_access"), controllers.VendorIndex)
		auth.POST("/vendors", middleware.RequirePermission("vendor_create"), controllers.VendorStore)
		auth.POST("/vendors/update", middleware.RequirePermission("vendor_edit"), controllers.VendorUpdate)
		auth.GET("/vendors/delete/:id", middleware.RequirePermission("vendor_delete"), controllers.VendorDelete)
		auth.GET("/gl-accounts", middleware.RequirePermission("gl_account_management_access"), controllers.GLAccountIndex)
		auth.POST("/gl-accounts", middleware.RequirePermission("gl_account_create"), controllers.GLAccountStore)
		auth.POST("/gl-accounts/update", middleware.RequirePermission("gl_account_edit"), controllers.GLAccountUpdate)
		auth.GET("/gl-accounts/delete/:id", middleware.RequirePermission("gl_account_delete"), controllers.GLAccountDelete)
		auth.GET("/divisions", middleware.RequirePermission("division_management_access"), controllers.DivisionIndex)
		auth.POST("/divisions", middleware.RequirePermission("division_create"), controllers.DivisionStore)
		auth.POST("/divisions/update", middleware.RequirePermission("division_edit"), controllers.DivisionUpdate)
		auth.GET("/divisions/delete/:id", middleware.RequirePermission("division_delete"), controllers.DivisionDelete)
		auth.GET("/budgets", middleware.RequirePermission("budget_management_access"), controllers.BudgetIndex)
		auth.POST("/budgets", middleware.RequirePermission("budget_create"), controllers.BudgetStore)
		auth.POST("/budgets/update", middleware.RequirePermission("budget_edit"), controllers.BudgetUpdate)
		auth.GET("/budgets/delete/:id", middleware.RequirePermission("budget_delete"), controllers.BudgetDelete)
		auth.GET("/store-approvers", middleware.RequirePermission("store_approver_management_access"), controllers.StoreApproverIndex)
		auth.POST("/store-approvers", middleware.RequirePermission("store_approver_create"), controllers.StoreApproverStore)
		auth.POST("/store-approvers/update", middleware.RequirePermission("store_approver_edit"), controllers.StoreApproverUpdate)
		auth.GET("/store-approvers/delete/:id", middleware.RequirePermission("store_approver_delete"), controllers.StoreApproverDelete)
		auth.GET("/approval-rules", middleware.RequirePermission("approval_rule_management_access"), controllers.ApprovalRuleIndex)
		auth.GET("/approval-rules/form", middleware.RequirePermission("approval_rule_create"), controllers.ApprovalRuleFormIndex)
		auth.GET("/approval-rules/:id/edit", middleware.RequirePermission("approval_rule_edit"), controllers.ApprovalRuleEdit)
		auth.POST("/approval-rules", middleware.RequirePermission("approval_rule_create"), controllers.ApprovalRuleStore)
		auth.POST("/approval-rules/update", middleware.RequirePermission("approval_rule_edit"), controllers.ApprovalRuleUpdate)
		auth.GET("/approval-rules/delete/:id", middleware.RequirePermission("approval_rule_delete"), controllers.ApprovalRuleDelete)
		auth.GET("/users", middleware.RequirePermission("user_management_access"), controllers.UserIndex)
		auth.POST("/users", middleware.RequirePermission("user_create"), controllers.UserStore)
		auth.POST("/users/update", middleware.RequirePermission("user_edit"), controllers.UserUpdate)
		auth.GET("/users/delete/:id", middleware.RequirePermission("user_delete"), controllers.UserDelete)
		auth.GET("/role", middleware.RequirePermission("role_management_access"), controllers.RoleIndex)
		auth.GET("/roleForm", middleware.RequirePermission("role_create"), controllers.RoleFormIndex)
		auth.GET("/role/:id/edit", middleware.RequirePermission("role_edit"), controllers.RoleEdit)
		auth.POST("/role", middleware.RequirePermission("role_create"), controllers.RoleStore)
		auth.POST("/role/update", middleware.RequirePermission("role_edit"), controllers.RoleUpdate)
		auth.GET("/role/delete/:id", middleware.RequirePermission("role_delete"), controllers.RoleDelete)
	}
}
