package routes

import (
	"gobase-app/controllers"
	"gobase-app/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterWebRoutes(r *gin.Engine) {
	r.Use(middleware.UserMiddleware())

	r.GET("/", controllers.LoginPage)
	r.GET("/login", controllers.LoginPage)
	r.POST("/login", controllers.LoginPost)
	r.GET("/logout", controllers.Logout)

	auth := r.Group("/")
	auth.Use(middleware.AuthRequired(), middleware.PermissionContext())
	{
		auth.GET("/profile", controllers.ProfileIndex)
		auth.POST("/profile", controllers.ProfileUpdate)
		auth.POST("/profile/password", controllers.ProfilePasswordUpdate)
		auth.GET("/dashboard", middleware.RequirePermission("dashboard_access"), controllers.DashboardIndex)
		auth.GET("/approval-tasks", middleware.RequirePermission("approval_task_management_access"), controllers.ApprovalTaskInboxIndex)
		auth.GET("/approval-tasks/:id", middleware.RequirePermission("approval_task_view"), controllers.ApprovalTaskDetail)
		auth.POST("/approval-tasks/:id/approve", middleware.RequirePermission("approval_task_approve"), controllers.ApprovalTaskApprove)
		auth.POST("/approval-tasks/:id/reject", middleware.RequirePermission("approval_task_reject"), controllers.ApprovalTaskReject)
		auth.GET("/purchase-requests", middleware.RequirePermission("purchase_request_management_access"), controllers.PurchaseRequestIndex)
		auth.GET("/purchase-requests/form", middleware.RequirePermission("purchase_request_create"), controllers.PurchaseRequestFormIndex)
		auth.GET("/purchase-requests/:id", middleware.RequirePermission("purchase_request_view"), controllers.PurchaseRequestDetailIndex)
		auth.POST("/purchase-requests/:id/update", middleware.RequirePermission("purchase_request_edit"), controllers.PurchaseRequestUpdate)
		auth.POST("/purchase-requests/:id/regenerate-approval", middleware.RequirePermission("purchase_request_management_access"), controllers.PurchaseRequestRegenerateApproval)
		auth.POST("/purchase-requests", middleware.RequirePermission("purchase_request_create"), controllers.PurchaseRequestStore)
		auth.GET("/purchase-orders", middleware.RequirePermission("purchase_order_management_access"), controllers.PurchaseOrderIndex)
		auth.GET("/purchase-orders/create-from-pr/:pr_id", middleware.RequirePermission("purchase_order_create"), controllers.PurchaseOrderCreateFromPR)
		auth.POST("/purchase-orders", middleware.RequirePermission("purchase_order_create"), controllers.PurchaseOrderStore)
		auth.GET("/purchase-orders/:id", middleware.RequirePermission("purchase_order_view"), controllers.PurchaseOrderDetailIndex)
		auth.GET("/asset-types", middleware.RequirePermission("asset_type_management_access"), controllers.AssetTypeIndex)
		auth.POST("/asset-types", middleware.RequirePermission("asset_type_create"), controllers.AssetTypeStore)
		auth.POST("/asset-types/update", middleware.RequirePermission("asset_type_edit"), controllers.AssetTypeUpdate)
		auth.GET("/asset-types/delete/:id", middleware.RequirePermission("asset_type_delete"), controllers.AssetTypeDelete)
		auth.GET("/component-types", middleware.RequirePermission("component_type_management_access"), controllers.ComponentTypeIndex)
		auth.POST("/component-types", middleware.RequirePermission("component_type_create"), controllers.ComponentTypeStore)
		auth.POST("/component-types/update", middleware.RequirePermission("component_type_edit"), controllers.ComponentTypeUpdate)
		auth.GET("/component-types/delete/:id", middleware.RequirePermission("component_type_delete"), controllers.ComponentTypeDelete)
		auth.GET("/asset-locations", middleware.RequirePermission("asset_location_management_access"), controllers.AssetLocationIndex)
		auth.POST("/asset-locations", middleware.RequirePermission("asset_location_create"), controllers.AssetLocationStore)
		auth.POST("/asset-locations/update", middleware.RequirePermission("asset_location_edit"), controllers.AssetLocationUpdate)
		auth.GET("/asset-locations/delete/:id", middleware.RequirePermission("asset_location_delete"), controllers.AssetLocationDelete)
		auth.GET("/asset-register", middleware.RequirePermission("asset_management_access"), controllers.AssetIndex)
		auth.POST("/asset-register", middleware.RequirePermission("asset_create"), controllers.AssetStore)
		auth.POST("/asset-register/update", middleware.RequirePermission("asset_edit"), controllers.AssetUpdate)
		auth.GET("/asset-register/delete/:id", middleware.RequirePermission("asset_delete"), controllers.AssetDelete)
		auth.GET("/asset-components", middleware.RequirePermission("asset_component_management_access"), controllers.AssetComponentIndex)
		auth.POST("/asset-components", middleware.RequirePermission("asset_component_create"), controllers.AssetComponentStore)
		auth.POST("/asset-components/update", middleware.RequirePermission("asset_component_edit"), controllers.AssetComponentUpdate)
		auth.GET("/asset-components/delete/:id", middleware.RequirePermission("asset_component_delete"), controllers.AssetComponentDelete)
		auth.GET("/asset-movements", middleware.RequirePermission("asset_movement_management_access"), controllers.AssetMovementIndex)
		auth.POST("/asset-movements", middleware.RequirePermission("asset_movement_create"), controllers.AssetMovementStore)
		auth.GET("/asset-component-movements", middleware.RequirePermission("asset_component_movement_management_access"), controllers.AssetComponentMovementIndex)
		auth.POST("/asset-component-movements", middleware.RequirePermission("asset_component_movement_create"), controllers.AssetComponentMovementStore)

		auth.POST("/register", middleware.RequirePermission("user_create"), controllers.CreateUser)
		auth.GET("/stores", middleware.RequirePermission("store_management_access"), controllers.StoreIndex)
		auth.POST("/stores", middleware.RequirePermission("store_create"), controllers.StoreStore)
		auth.POST("/stores/update", middleware.RequirePermission("store_edit"), controllers.StoreUpdate)
		auth.GET("/stores/delete/:id", middleware.RequirePermission("store_delete"), controllers.StoreDelete)
		auth.GET("/vendors", middleware.RequirePermission("vendor_management_access"), controllers.VendorIndex)
		auth.POST("/vendors", middleware.RequirePermission("vendor_create"), controllers.VendorStore)
		auth.POST("/vendors/update", middleware.RequirePermission("vendor_edit"), controllers.VendorUpdate)
		auth.GET("/vendors/delete/:id", middleware.RequirePermission("vendor_delete"), controllers.VendorDelete)
		auth.GET("/gl-accounts", middleware.RequirePermission("gl_account_management_access"), controllers.GLAccountIndex)
		auth.POST("/gl-accounts", middleware.RequirePermission("gl_account_create"), controllers.GLAccountStore)
		auth.POST("/gl-accounts/update", middleware.RequirePermission("gl_account_edit"), controllers.GLAccountUpdate)
		auth.GET("/gl-accounts/delete/:id", middleware.RequirePermission("gl_account_delete"), controllers.GLAccountDelete)
		auth.GET("/divisions", middleware.RequirePermission("division_management_access"), controllers.DivisionIndex)
		auth.POST("/divisions", middleware.RequirePermission("division_create"), controllers.DivisionStore)
		auth.POST("/divisions/update", middleware.RequirePermission("division_edit"), controllers.DivisionUpdate)
		auth.GET("/divisions/delete/:id", middleware.RequirePermission("division_delete"), controllers.DivisionDelete)
		auth.GET("/budgets", middleware.RequirePermission("budget_management_access"), controllers.BudgetIndex)
		auth.POST("/budgets", middleware.RequirePermission("budget_create"), controllers.BudgetStore)
		auth.POST("/budgets/update", middleware.RequirePermission("budget_edit"), controllers.BudgetUpdate)
		auth.GET("/budgets/delete/:id", middleware.RequirePermission("budget_delete"), controllers.BudgetDelete)
		auth.GET("/store-approvers", middleware.RequirePermission("store_approver_management_access"), controllers.StoreApproverIndex)
		auth.POST("/store-approvers", middleware.RequirePermission("store_approver_create"), controllers.StoreApproverStore)
		auth.POST("/store-approvers/update", middleware.RequirePermission("store_approver_edit"), controllers.StoreApproverUpdate)
		auth.GET("/store-approvers/delete/:id", middleware.RequirePermission("store_approver_delete"), controllers.StoreApproverDelete)
		auth.GET("/approval-rules", middleware.RequirePermission("approval_rule_management_access"), controllers.ApprovalRuleIndex)
		auth.GET("/approval-rules/form", middleware.RequirePermission("approval_rule_create"), controllers.ApprovalRuleFormIndex)
		auth.GET("/approval-rules/:id/edit", middleware.RequirePermission("approval_rule_edit"), controllers.ApprovalRuleEdit)
		auth.POST("/approval-rules", middleware.RequirePermission("approval_rule_create"), controllers.ApprovalRuleStore)
		auth.POST("/approval-rules/update", middleware.RequirePermission("approval_rule_edit"), controllers.ApprovalRuleUpdate)
		auth.GET("/approval-rules/delete/:id", middleware.RequirePermission("approval_rule_delete"), controllers.ApprovalRuleDelete)
		auth.GET("/users", middleware.RequirePermission("user_management_access"), controllers.UserIndex)
		auth.POST("/users", middleware.RequirePermission("user_create"), controllers.UserStore)
		auth.POST("/users/update", middleware.RequirePermission("user_edit"), controllers.UserUpdate)
		auth.GET("/users/delete/:id", middleware.RequirePermission("user_delete"), controllers.UserDelete)
		auth.GET("/role", middleware.RequirePermission("role_management_access"), controllers.RoleIndex)
		auth.GET("/roleForm", middleware.RequirePermission("role_create"), controllers.RoleFormIndex)
		auth.GET("/role/:id/edit", middleware.RequirePermission("role_edit"), controllers.RoleEdit)
		auth.POST("/role", middleware.RequirePermission("role_create"), controllers.RoleStore)
		auth.POST("/role/update", middleware.RequirePermission("role_edit"), controllers.RoleUpdate)
		auth.GET("/role/delete/:id", middleware.RequirePermission("role_delete"), controllers.RoleDelete)
	}
}
